### ISSUE TITLE
Issue: Fondo en el formulario 

### ISSUE THREAD

**Issue by ValleGalan** [Okysnm/template#1]
![image](https://user-images.githubusercontent.com/77822150/177447821-ec7ea9a5-6708-4148-b10f-d349ab629bd2.png)
 Pondre un fondo en el formulario y un color en el hover para que al pasar por encima del botón no se pierda con el fondo verde.

**Comment by ValleGalan** [comment]
Tambien se agrego la parte de texnologias con el archivo icon.

**Comment by Okysnm** [comment]
hola perdon por la demora, ok con los cambios
